apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ28tYWRtaW4=          # base64 for 'mongoadmin', command to encode: echo -n 'mongoadmin' | base64
  mongo-root-password: cGFzc3dyb2Q=      # base64 for 'password'
